# Generated by Django 4.2.23 on 2025-08-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_backtests',
            field=models.IntegerField(default=0),
        ),
    ]
