# Generated by Django 4.2.23 on 2025-08-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_total_backtests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium')], default='free', max_length=10),
        ),
    ]
