version: "1.0"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - flux-network

networks:
  flux-network:
    driver: bridge
